### ISSUE TITLE
Sounds bug for CSS

### ISSUE THREAD

**Issue by wladimir77** [Stewart-Anubis/Sm-Zombiereloaded-3-Franug-Anubis-Edition#4]
zombiereloaded_sounds.cfg
Você pode fechar o do CS GO, escrevi no lugar errado sobre o bug, preciso do CSS. Suplico com mais detalhes qual é o problema: havia um plugin do Franc1sco. Lá, um arquivo até zombie_bite.mp3 foi registrado no cfg. Eu carreguei seu plugin em um servidor limpo, configurei escrevendo o que eu preciso em zombiereloaded_sounds.cfg, ele comeu tudo (funciona), exceto pelo som de infecção. Ele faz o upload do servidor, mas você não consegue ouvir no cliente. Foi baixado do zero, eu instalei antes, do Franc1sco. Ele jogou, mas muito baixinho, e mesmo se você estiver por perto. Antes da atualização em 25/05/21, ele era ouvido corretamente em todos os lugares.
PS
Ainda assim, os sons seriam mais estendidos para complementar: ao entrar no servidor e ao início da rodada. E então, no final, há uma rodada.
Veja como o tempo não é crítico.

**Comment by wladimir77** [comment]
Infelizmente, não posso escrever no branch sm-zombiereloaded-3-Franug-Edition, chego ao repositório do proprietário. Achei que estava escrevendo para você, mas acho que o cara ficará surpreso. :) Queria falar sobre ela e acima escrevi um erro com uma descrição detalhada.

**Comment by Stewart-Anubis** [comment]
Bom dia , estava tentando entender seu problema , me adiciona no Discord Анубис#0446 .
